### ISSUE TITLE
Are you considering submitting a pull request?

### ISSUE THREAD

**Issue by Rubonnek** [Stary2001/godot#17]
I'd love to see this merged into upstream.

**Comment by Stary2001** [comment]
Whoops, it seems I missed this issue...
It's a bit complicated - the Godot maintainers have previously said they won't take console ports in tree due to NDA/SDK licensing reasons(https://docs.godotengine.org/en/3.2/tutorials/platform/consoles.html).
That would mean a homebrew port is completely fine by those standards.
Another potential issue is if this port would conflict with the official Switch port at all, or even if Nintendo dislikes it.
I haven't talked to the developers about this and also haven't really been putting much time into this port as of late.

**Comment by Rubonnek** [comment]
I see. I was aware of the NDA/SDK licensing reasons, but I wasn't aware that the maintainers wouldn't take homebrew ports.

But yeah, if Nintendo dislikes it, I'm sure they would pull their attorney's weight on the matter given that Nintendo has shutdown many fan-made games.

Thanks for the clarification.
