### ISSUE TITLE
Why not define `UNIX_ENABLED` as well?

### ISSUE THREAD

**Issue by halotroop2288** [Stary2001/godot#31]
Most of the changes outside of the `platform` directory seem to be adding `|| defined(HORIZON_ENABLED)` to lines that already have `defined(UNIX_ENABLED)`. Is there any reason you don't simply add the Unix define [here](https://github.com/Stary2001/godot/blob/3.5.1-stable_switch/platform/switch/detect.py#L246)  to avoid most of those edits? Or is it just that Horizon isn't fully Unix-compatible?

**Comment by Stary2001** [comment]
When I was doing the initial port I treated the Switch as a separate platform, because there is a lot of stuff that is different to  a "normal" Linux/etc system (and when I started it there wasn't even pthread compatibility).
It's slightly more compatible now but still missing a bunch of stuff (dynamic libraries, syslog, etc..).
Hope that helps.
